[[task]]
id = 1
task_name = "handle hardware interrupts"
completion = true

[[task]]
id = 2
task_name = "implement paging"
completion = true

[[task]]
id = 3
task_name = "fix holding enter being faster than the prompt can appear"
completion = true

[[task]]
id = 4
task_name = "handle backspace"
completion = true

[[task]]
id = 5
task_name = "fix deadlock on typing stuff before it fully boots up"
completion = false

[[task]]
id = 6
task_name = "make docs (probably never)"
completion = false
